name: 'Push'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - 'package.json'
      - 'tsconfig*.json'

env:
  KEYSTORE_HOST: '${{ secrets.KEYSTORE_HOST }}'
  KEYSTORE_ACCESS_TOKEN: '${{ secrets.KEYSTORE_ACCESS_TOKEN }}'

jobs:
  Publish:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - name: 'Load code'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 2
      - name: 'Setup Node'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: 'true'
      - name: 'Install dependencies'
        run: 'npm install'
      - name: 'Format code'
        run: 'npm run format'
      - name: 'Build'
        run: 'npm run build'
      - name: 'Publish'
        run: 'chmod +x scripts/publish.sh && scripts/publish.sh'
